name: Run PNPM Command

on:
  workflow_call:
    inputs:
      commands:
        type: 'string'
        description: |
          A JSON array of package.json scripts, e.g.
          '["lint","test","types"]'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ${{ fromJson(inputs.commands) }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Run ${{ matrix.command }}
        run: pnpm run "${{env.COMMAND}}"
        env:
          COMMAND: ${{ matrix.command }}