name: Run PNPM Command

on:
  workflow_call:
    inputs:
      commands:
        type: 'string'
        description: |
          A JSON array of package.json scripts, e.g.
          '["lint","test","types"]'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ${{ fromJson(inputs.commands) }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@main

      - name: Run ${{ matrix.command }}
        run: pnpm run "${{env.COMMAND}}"
        env:
          COMMAND: ${{ matrix.command }}